package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.DockerCommandStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        maven {
            goals = "clean package"
            mavenVersion = auto()
        }
        dockerCommand {
            name = "Build Image"
            commandType = build {
                source = file {
                    path = "Dockerfile"
                }
                namesAndTags = "app_test"
                commandArgs = "--pull"
            }
            param("dockerImage.platform", "linux")
        }
    }
    steps {
        update<DockerCommandStep>(1) {
            commandType = build {
                source = file {
                    path = "Dockerfile"
                }
                contextDir = ""
                namesAndTags = "app_testsss"
                commandArgs = "--pull"
            }
        }
    }
}
